# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 08:43
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
