# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0008_auto_20180621_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_pic',
            field=models.ImageField(default='Image', upload_to='p/'),
        ),
    ]
