# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 08:52
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0009_auto_20180621_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_pic',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
