# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 11:56
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0012_auto_20180621_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
