# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 12:25
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0013_auto_20180621_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True, default='http://planetbotanix.com/wp-content/uploads/2017/08/Female-Avatar-1-300x300.jpg'),
        ),
    ]
